### ISSUE TITLE
Error: yarn start --listing ./out

### ISSUE THREAD

**Issue by bugrevealingbme** [QuentinRoy/phonearena-scrapper#1]
[Error: EISDIR: illegal operation on a directory, read] errno: -4068, code: 'EISDIR', syscall: 'read' }
Thanks

**Comment by QuentinRoy** [comment]
Don't provide a listing file unless you have one. This file is supposed to be created by the scrapper itself. This option enables to skip this step if you already did it. I suspect this the origin of thos error.

**Comment by bugrevealingbme** [comment]
Thank you for the quick reply. I need a list of all devices or features CSV or SQL file required

**Comment by QuentinRoy** [comment]
Just launch `yarn start` then. It will take a few hours too scrap the entire database. It produces json files however.

**Comment by bugrevealingbme** [comment]
It's finished now. Where is SQL or csv?

**Comment by QuentinRoy** [comment]
There is none. It produces JSON.

**Comment by bugrevealingbme** [comment]
Oh. Json is useless. Then we need a list of all devices. How do I get a link to all devices?

**Comment by QuentinRoy** [comment]
No it isn't.

You look inside the JSONs, and/or you write a script to extract what you need.
I wrote one in the past. It is in `script-utils`. Might be a good way to start, and maybe it will fit your needs.

**Comment by bugrevealingbme** [comment]
> No it isn't. You look inside the JSONs, and/or you write a script to extract what you need. I wrote one in the past. It is in `script-utils`. Might be a good way to start, and maybe it will fit your needs.
> […](#)
> On Feb 13, 2019, at 07:50, bugrevealingbme ***@***.***> wrote: Oh. Json is useless. Then we need a list of all devices. How do I get a link to all devices? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

The only problem I do not know NodeJS :(

**Comment by bugrevealingbme** [comment]
I think it wouldn't be too hard for you. If you're exporting all the links, I'd be grateful

**Comment by QuentinRoy** [comment]
I would recommend you try my export script, `yarn export-for-visu` (it needs the data to be already scrapped), and see if it fits your needs. It will export one csv file and put it at `visu/phones.csv`.
If it does it is perfect. If it does not I am sorry but you will have to do the rest yourself. I do not have the time to do your work :).

**Comment by bugrevealingbme** [comment]
Thanks worked. How do I run csv-export in Script utils?

**Comment by QuentinRoy** [comment]
`yarn export-for-visu` runs it
